import './bootstrap';
import './charts.js';
import './echo.js';
import './admin/administrators-realtime.js';
import './admin/reporters-realtime.js';
import './admin/students-realtime.js';
import './admin/staff-realtime.js';
import './admin/security-realtime.js';
import './admin/stakeholders-realtime.js';
import './admin/vehicles.js';
import './admin/vehicles-realtime.js';
import './admin/stickers-realtime.js';
import './utils/error-handler.js';
import './utils/form-loader.js';
import './utils/form-validator.js';
import './utils/keyboard-shortcuts.js';
import './admin/colleges-realtime.js';
import './admin/programs-realtime.js';
import './admin/vehicle-types-realtime.js';
import './admin/location-types-realtime.js';
import './admin/fees-realtime.js';
import './admin/patrol-logs-realtime.js';
import './admin/reports-realtime.js';
import './admin/campus-map-realtime.js';
import './reporter/my-vehicles-realtime.js';
import './reporter/my-reports-realtime.js';

// Settings modules
import './settings/main.js';
import './settings/appearance.js';
import './settings/notifications.js';
import './settings/college.js';
import './settings/program.js';
import './settings/vehicle-type.js';
import './settings/fees.js';
import './settings/security.js';
// import './template/tables.js';
// import './template/modals.js';
// import './template/media.js';
// import './template/qr-scanner.js';
// import './template/registration.js';
import './auth/password-toggle.js';
